//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEliteWebAcceso.Application.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiEliteWebAcceso.Application.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Token no valido..
        /// </summary>
        public static string ArchivoTokenInvalid {
            get {
                return ResourceManager.GetString("ArchivoTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro eliminado exitosamente..
        /// </summary>
        public static string DeleteCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DeleteCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento y/o password incorrectos..
        /// </summary>
        public static string DocumentoOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("DocumentoOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo eliminar el registro..
        /// </summary>
        public static string NotDeleteGeneric {
            get {
                return ResourceManager.GetString("NotDeleteGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros..
        /// </summary>
        public static string NotRegisteredGeneric {
            get {
                return ResourceManager.GetString("NotRegisteredGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo actualizar el registro..
        /// </summary>
        public static string NotUpdateGeneric {
            get {
                return ResourceManager.GetString("NotUpdateGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro {0} es requerido..
        /// </summary>
        public static string ParameterRequired {
            get {
                return ResourceManager.GetString("ParameterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro creado exitosamente..
        /// </summary>
        public static string RegisterCreatedSuccessfully {
            get {
                return ResourceManager.GetString("RegisterCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro actualizado exitosamente..
        /// </summary>
        public static string UpdateCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdateCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se encuentra registrado un usuario con ese número de documento..
        /// </summary>
        public static string UsuarioDocumentoExiste {
            get {
                return ResourceManager.GetString("UsuarioDocumentoExiste", resourceCulture);
            }
        }
    }
}
